<?php
/*to add more refer http://www.freeformatter.com/mime-types-list.html*/
$mime = array("html" => "text/html",
		"css" => "text/css",
		"js" => "application/javascript",
		"json" => "application/json",
		"jpg" => "image/jpeg",
		"jpeg" => "image/jpeg",
		"swf" => "application/x-shockwave-flash",
		"pdf" => "application/pdf",
		"bmp" => "image/bmp",
		"png" => "image/png",
		"sh" => "application/x-sh",
		"ico" => "image/x-icon",
		"gif" => "image/gif",
		"au" => "audio/basic",
		"avi" => "video/avi",
		"doc" => "application/msword",
		"mp3" => "audio/mpeg",
		"mpeg" => "video/mpeg",
		"ppt" => "application/vnd.ms-powerpoint",
		"rtf" => "application/rtf",
		"txt" => "text/plain",
		"wav" => "audio/wav",
		"xls" => "application/vnd.ms-excel",
		"xml" => "application/xml",
		"zip" => "application/zip");
